// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8FO9cne6wt2dOd0UzmudxeJ0yCu1oFz4',
    appId: '1:246821847720:web:b28abd361a40a0226ab89d',
    messagingSenderId: '246821847720',
    projectId: 'my-portfolio-website-78089',
    authDomain: 'my-portfolio-website-78089.firebaseapp.com',
    storageBucket: 'my-portfolio-website-78089.firebasestorage.app',
    measurementId: 'G-BG8WRDFB21',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1JApL9KDLJq8-q06xDpW-Gx5r2BlFD1c',
    appId: '1:246821847720:android:81c23ee7b78460d96ab89d',
    messagingSenderId: '246821847720',
    projectId: 'my-portfolio-website-78089',
    storageBucket: 'my-portfolio-website-78089.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBydU7tUM9LtfixkjnDQafjXfIl0U_HZAk',
    appId: '1:246821847720:ios:e7ea82caa9cd92806ab89d',
    messagingSenderId: '246821847720',
    projectId: 'my-portfolio-website-78089',
    storageBucket: 'my-portfolio-website-78089.firebasestorage.app',
    iosBundleId: 'com.example.portfolioWebsite',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBydU7tUM9LtfixkjnDQafjXfIl0U_HZAk',
    appId: '1:246821847720:ios:e7ea82caa9cd92806ab89d',
    messagingSenderId: '246821847720',
    projectId: 'my-portfolio-website-78089',
    storageBucket: 'my-portfolio-website-78089.firebasestorage.app',
    iosBundleId: 'com.example.portfolioWebsite',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB8FO9cne6wt2dOd0UzmudxeJ0yCu1oFz4',
    appId: '1:246821847720:web:a93d588a7ea571456ab89d',
    messagingSenderId: '246821847720',
    projectId: 'my-portfolio-website-78089',
    authDomain: 'my-portfolio-website-78089.firebaseapp.com',
    storageBucket: 'my-portfolio-website-78089.firebasestorage.app',
    measurementId: 'G-E079RBX4TM',
  );
}
